import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { ArrowDownRight, ArrowUpRight, Landmark } from "lucide-react";
import { getReceivables } from "@/lib/financial.functions";
import { brl } from "@/lib/format";
export const Route=createFileRoute("/_authenticated/admin/fluxo-caixa")({head:()=>({meta:[{title:"Fluxo de caixa · Norte Sul"}]}),component:CashFlow});
const date=(v:string)=>new Date(v+"T12:00:00").toLocaleDateString("pt-BR");
function CashFlow(){const get=useServerFn(getReceivables),q=useQuery({queryKey:["cash-flow"],queryFn:()=>get()});const r=q.data?.receivables??[],p=q.data?.expenses??[];const incomingOpen=r.filter((x:any)=>x.status==="open").reduce((s:number,x:any)=>s+Number(x.amount),0),incomingDone=r.filter((x:any)=>x.status==="received").reduce((s:number,x:any)=>s+Number(x.amount),0),outOpen=p.filter((x:any)=>x.status==="open").reduce((s:number,x:any)=>s+Number(x.amount),0),outDone=p.filter((x:any)=>x.status==="paid").reduce((s:number,x:any)=>s+Number(x.amount),0);const events=[...r.map((x:any)=>({id:"r"+x.id,date:x.status==="received"?(x.received_at??x.due_date):x.due_date,description:x.description+" · "+x.customer_name,type:"in",amount:Number(x.amount),status:x.status})),...p.map((x:any)=>({id:"p"+x.id,date:x.status==="paid"?(x.paid_at??x.due_date):x.due_date,description:x.description,type:"out",amount:Number(x.amount),status:x.status}))].sort((a:any,b:any)=>String(b.date).localeCompare(String(a.date)));
return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Financeiro</p><h1 className="mt-1 flex items-center gap-2 font-display text-3xl font-extrabold"><Landmark className="h-7 w-7 text-emerald-600"/> Fluxo de caixa</h1><p className="mt-1 text-sm text-muted-foreground">Visão consolidada de entradas e saídas. O saldo é financeiro, não saldo bancário conciliado.</p></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card label="A receber" value={incomingOpen} tone="amber"/><Card label="Recebido" value={incomingDone} tone="emerald"/><Card label="A pagar" value={outOpen} tone="rose"/><Card label="Pago" value={outDone} tone="slate"/></section><section className="rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Movimentações financeiras</h2><p className="text-sm text-slate-500">Entradas e saídas registradas, ordenadas por data.</p></div><div className="divide-y">{events.map((x:any)=><div key={x.id} className="flex items-center justify-between gap-4 p-4"><div className="flex items-center gap-3">{x.type==="in"?<ArrowUpRight className="h-5 w-5 text-emerald-600"/>:<ArrowDownRight className="h-5 w-5 text-rose-600"/>}<div><b className="text-sm">{x.description}</b><div className="text-xs text-slate-500">{date(String(x.date).slice(0,10))} · {x.status==="received"||x.status==="paid"?"Realizado":"Previsto"}</div></div></div><span className={"font-bold "+(x.type==="in"?"text-emerald-700":"text-rose-700")}>{x.type==="in"?"+":"-"} {brl(x.amount)}</span></div>)}{!q.isLoading&&!events.length&&<p className="p-8 text-center text-sm text-slate-500">Sem movimentações financeiras.</p>}</div></section></div>}
function Card({label,value,tone}:{label:string,value:number,tone:string}){const colors:any={amber:"border-amber-200 bg-amber-50",emerald:"border-emerald-200 bg-emerald-50",rose:"border-rose-200 bg-rose-50",slate:"border-slate-200 bg-slate-50"};return <div className={"rounded-2xl border p-5 "+colors[tone]}><p className="text-sm font-semibold text-slate-600">{label}</p><p className="mt-2 text-2xl font-extrabold">{brl(value)}</p></div>}