import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { CircleDollarSign, FolderTree, Plus, Tag } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { getFinancialSetup, saveCostCenter, saveExpenseCategory } from "@/lib/financial.functions";

export const Route=createFileRoute("/_authenticated/admin/financeiro")({head:()=>({meta:[{title:"Financeiro · Norte Sul"}]}),component:FinancialSetup});
function FinancialSetup(){
 const qc=useQueryClient(),get=useServerFn(getFinancialSetup),saveCenter=useServerFn(saveCostCenter),saveCategory=useServerFn(saveExpenseCategory);
 const [center,setCenter]=useState(""),[category,setCategory]=useState(""),[kind,setKind]=useState<"fixed"|"variable">("fixed");
 const q=useQuery({queryKey:["financial-setup"],queryFn:()=>get()});
 const refresh=()=>qc.invalidateQueries({queryKey:["financial-setup"]});
 const c=useMutation({mutationFn:()=>saveCenter({data:{name:center}}),onSuccess:()=>{toast.success("Centro de custo criado");setCenter("");refresh()},onError:(e:Error)=>toast.error(e.message)});
 const cat=useMutation({mutationFn:()=>saveCategory({data:{name:category,default_kind:kind}}),onSuccess:()=>{toast.success("Categoria criada");setCategory("");refresh()},onError:(e:Error)=>toast.error(e.message)});
 return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">Financeiro</p><h1 className="mt-1 flex items-center gap-2 font-display text-3xl font-extrabold"><CircleDollarSign className="h-7 w-7 text-emerald-600"/> Estrutura financeira</h1><p className="mt-1 text-sm text-muted-foreground">Base para contas a pagar, fluxo de caixa, rateio e preço real.</p></header><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex gap-3"><FolderTree className="h-5 w-5 text-blue-600"/><div><h2 className="font-bold">Centros de custo</h2><p className="text-sm text-muted-foreground">Onde a despesa aconteceu.</p></div></div><div className="mt-4 flex gap-2"><input className="w-full rounded-xl border px-3 py-2 text-sm" value={center} onChange={e=>setCenter(e.target.value)} placeholder="Ex.: Nova filial"/><button disabled={!center||c.isPending} onClick={()=>c.mutate()} className="rounded-xl bg-blue-600 px-3 text-white disabled:opacity-50"><Plus className="h-4 w-4"/></button></div><div className="mt-4 flex flex-wrap gap-2">{(q.data?.centers??[]).map((x:any)=><span key={x.id} className="rounded-full bg-blue-50 px-3 py-1.5 text-sm font-medium text-blue-800">{x.name}</span>)}</div></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex gap-3"><Tag className="h-5 w-5 text-violet-600"/><div><h2 className="font-bold">Categorias financeiras</h2><p className="text-sm text-muted-foreground">O que a despesa representa no resultado.</p></div></div><div className="mt-4 grid grid-cols-[1fr_auto_auto] gap-2"><input className="min-w-0 rounded-xl border px-3 py-2 text-sm" value={category} onChange={e=>setCategory(e.target.value)} placeholder="Nova categoria"/><select className="rounded-xl border px-2 text-sm" value={kind} onChange={e=>setKind(e.target.value as any)}><option value="fixed">Fixa</option><option value="variable">Variável</option></select><button disabled={!category||cat.isPending} onClick={()=>cat.mutate()} className="rounded-xl bg-violet-600 px-3 text-white disabled:opacity-50"><Plus className="h-4 w-4"/></button></div><div className="mt-4 flex flex-wrap gap-2">{(q.data?.categories??[]).map((x:any)=><span key={x.id} className={`rounded-full px-3 py-1.5 text-sm font-medium ${x.default_kind==="fixed"?"bg-amber-50 text-amber-800":"bg-emerald-50 text-emerald-800"}`}>{x.name} · {x.default_kind==="fixed"?"fixa":"variável"}</span>)}</div></section></div><section className="rounded-2xl border border-dashed bg-slate-50 p-5"><h2 className="font-bold">Próxima etapa: contas a pagar</h2><p className="mt-1 text-sm text-muted-foreground">Lançamentos de boleto, gasto, vencimento, recorrência, baixa e anexo. Esta estrutura já está preparada para receber esses títulos.</p></section></div>
}