import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useRef } from "react";
import { useServerFn } from "@tanstack/react-start";
import { BarChart3, Bot, MonitorSmartphone, ScanLine, ShoppingBag, Trophy, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { getSalesSummary, getSiteSaleAlerts } from "@/lib/sales-summary.functions";

export const Route=createFileRoute("/_authenticated/admin/resumo-vendas")({head:()=>({meta:[{title:"Resumo de vendas · Norte Sul"}]}),component:SalesSummary});
const brl=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const origin={site:{label:"Site",icon:MonitorSmartphone,tone:"bg-blue-50 text-blue-700"},ia:{label:"IA",icon:Bot,tone:"bg-violet-50 text-violet-700"},balcao:{label:"Balcão",icon:ScanLine,tone:"bg-emerald-50 text-emerald-700"}} as const;

function SalesSummary(){
 const salesFn=useServerFn(getSalesSummary),alertsFn=useServerFn(getSiteSaleAlerts),seen=useRef<Set<string>|null>(null);
 const q=useQuery({queryKey:["sales-summary",30],queryFn:()=>salesFn({data:{days:30}}),refetchInterval:60_000}),data:any=q.data;
 useEffect(()=>{let live=true;const check=async()=>{try{const rows:any[]=await alertsFn();if(!live)return;const ids=new Set(rows.map(x=>x.id));if(!seen.current){seen.current=ids;return}for(const sale of rows.filter(x=>!seen.current?.has(x.id)).reverse()){try{const Ctx=window.AudioContext||(window as any).webkitAudioContext,ctx=new Ctx(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=880;g.gain.setValueAtTime(.12,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.22);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.22);window.setTimeout(()=>void ctx.close(),300)}catch{}toast.success(`Nova venda no site · ${brl(Number(sale.total??0))}`,{description:sale.customer_name||"Pagamento confirmado",duration:10000})}seen.current=new Set([...(seen.current??[]),...ids])}catch{}};void check();const timer=window.setInterval(()=>void check(),15000);return()=>{live=false;window.clearInterval(timer)}},[alertsFn]);
 if(q.isLoading)return <div className="p-6 text-sm text-muted-foreground">Carregando vendas consolidadas…</div>;
 if(q.isError||!data)return <div className="m-6 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">Não foi possível carregar o resumo.</div>;
 const cards=[["Faturamento consolidado",brl(data.total.gross),WalletCards,"bg-slate-950 text-white"],["Vendas realizadas",String(data.total.orders),ShoppingBag,"bg-blue-600 text-white"],["Ticket médio",brl(data.total.averageTicket),BarChart3,"bg-violet-600 text-white"],["Site aguardando pagamento",String(data.pendingSiteOrders),MonitorSmartphone,"bg-amber-500 text-slate-950"]] as const;
 return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-700">Central comercial</p><h1 className="mt-1 text-3xl font-black text-slate-950">Resumo de vendas</h1><p className="mt-1 text-sm text-slate-500">Site, IA e balcão nos últimos {data.periodDays} dias.</p></div><Link to="/admin/pedidos" className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold">Ver pedidos</Link></header>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon,tone])=><article key={label} className={`rounded-2xl p-5 shadow-sm ${tone}`}><Icon className="h-5 w-5 opacity-80"/><p className="mt-5 text-xs font-bold uppercase opacity-75">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></article>)}</section>
  <section className="grid gap-4 lg:grid-cols-3">{(["site","ia","balcao"] as const).map(key=>{const x=origin[key],Icon=x.icon,v=data.origins[key],share=data.total.gross?Math.round(v.gross/data.total.gross*100):0;return <article key={key} className="rounded-2xl border bg-white p-5 shadow-sm"><span className={`inline-flex items-center gap-2 rounded-full px-3 py-1 text-xs font-black ${x.tone}`}><Icon className="h-3.5 w-3.5"/>{x.label}</span><p className="mt-5 text-2xl font-black">{brl(v.gross)}</p><div className="mt-2 flex justify-between text-sm text-slate-500"><span>{v.orders} venda(s)</span><span>{share}% do total</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${share}%`}}/></div></article>})}</section>
  <section className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><article className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center gap-2 border-b p-5"><Trophy className="h-5 w-5 text-amber-500"/><div><h2 className="font-black">Produtos mais vendidos</h2><p className="text-xs text-slate-500">Quantidade e faturamento de todas as origens.</p></div></div><div className="divide-y">{data.topProducts.length?data.topProducts.map((p:any,i:number)=><div key={`${p.sku}-${p.name}`} className="flex items-center gap-3 p-4"><span className="grid size-8 place-items-center rounded-lg bg-slate-100 text-xs font-black">{i+1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{p.name}</p><p className="font-mono text-xs text-slate-400">{p.sku||"sem SKU"}</p></div><div className="text-right"><p className="text-sm font-black">{p.quantity} un.</p><p className="text-xs text-slate-500">{brl(p.revenue)}</p></div></div>):<p className="p-8 text-center text-sm text-slate-500">Ainda não há produtos vendidos no período.</p>}</div></article>
  <article className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-black">Últimas vendas</h2><p className="text-xs text-slate-500">Atualizado a cada minuto.</p></div><div className="divide-y">{data.latestSales.length?data.latestSales.map((sale:any)=>{const x=origin[sale.origin as keyof typeof origin],Icon=x.icon;return <div key={`${sale.origin}-${sale.id}`} className="flex gap-3 p-4"><span className={`grid size-9 place-items-center rounded-xl ${x.tone}`}><Icon className="h-4 w-4"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{sale.customer}</p><p className="text-xs text-slate-500">{x.label} · {String(sale.status).replaceAll("_"," ")}</p></div><div className="text-right"><p className="text-sm font-black">{brl(Number(sale.total))}</p><p className="text-[11px] text-slate-400">{new Date(sale.createdAt).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}</p></div></div>}):<p className="p-8 text-center text-sm text-slate-500">Nenhuma venda no período.</p>}</div></article></section>
 </div>
}