/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AtivacaoRouteImport } from './routes/ativacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedVendedorRouteImport } from './routes/_authenticated/vendedor'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as BrandSocialDotwebpRouteImport } from './routes/brand/social[.]webp'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'
import { Route as AuthenticatedAdminBlingRouteImport } from './routes/_authenticated/admin.bling'
import { Route as AuthenticatedAdminCadastrosB2bRouteImport } from './routes/_authenticated/admin.cadastros-b2b'
import { Route as AuthenticatedAdminCatalogoFabricantesRouteImport } from './routes/_authenticated/admin.catalogo-fabricantes'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated/admin.cupons'
import { Route as AuthenticatedAdminEcossistemaRouteImport } from './routes/_authenticated/admin.ecossistema'
import { Route as AuthenticatedAdminEnriquecimentoProdutosRouteImport } from './routes/_authenticated/admin.enriquecimento-produtos'
import { Route as AuthenticatedAdminEstoqueRouteImport } from './routes/_authenticated/admin.estoque'
import { Route as AuthenticatedAdminExpedicaoRouteImport } from './routes/_authenticated/admin.expedicao'
import { Route as AuthenticatedAdminFiliaisRouteImport } from './routes/_authenticated/admin.filiais'
import { Route as AuthenticatedAdminFiscalRouteImport } from './routes/_authenticated/admin.fiscal'
import { Route as AuthenticatedAdminFiscalProdutosRouteImport } from './routes/_authenticated/admin.fiscal-produtos'
import { Route as AuthenticatedAdminFornecedoresRouteImport } from './routes/_authenticated/admin.fornecedores'
import { Route as AuthenticatedAdminHistoricoCustosRouteImport } from './routes/_authenticated/admin.historico-custos'
import { Route as AuthenticatedAdminHomologacaoRouteImport } from './routes/_authenticated/admin.homologacao'
import { Route as AuthenticatedAdminIaAesBusinessRouteImport } from './routes/_authenticated/admin.ia-aes-business'
import { Route as AuthenticatedAdminInteligenciaComercialRouteImport } from './routes/_authenticated/admin.inteligencia-comercial'
import { Route as AuthenticatedAdminMarcasRouteImport } from './routes/_authenticated/admin.marcas'
import { Route as AuthenticatedAdminMigracaoBlingRouteImport } from './routes/_authenticated/admin.migracao-bling'
import { Route as AuthenticatedAdminOrcamentosRouteImport } from './routes/_authenticated/admin.orcamentos'
import { Route as AuthenticatedAdminPdvRouteImport } from './routes/_authenticated/admin.pdv'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminPromocoesRouteImport } from './routes/_authenticated/admin.promocoes'
import { Route as AuthenticatedAdminReposicaoRouteImport } from './routes/_authenticated/admin.reposicao'
import { Route as AuthenticatedAdminRevisaoCodigosRouteImport } from './routes/_authenticated/admin.revisao-codigos'
import { Route as AuthenticatedAdminSaneamentoRouteImport } from './routes/_authenticated/admin.saneamento'
import { Route as AuthenticatedAdminSaneamentoCustosRouteImport } from './routes/_authenticated/admin.saneamento-custos'
import { Route as AuthenticatedAdminSuprimentosRouteImport } from './routes/_authenticated/admin.suprimentos'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminVendedoresRouteImport } from './routes/_authenticated/admin.vendedores'
import { Route as AuthenticatedVendedorIndexRouteImport } from './routes/_authenticated/vendedor.index'
import { Route as AuthenticatedVendedorClientesRouteImport } from './routes/_authenticated/vendedor.clientes'
import { Route as AuthenticatedVendedorMeusPedidosRouteImport } from './routes/_authenticated/vendedor.meus-pedidos'
import { Route as AuthenticatedVendedorPedidoAssistidoRouteImport } from './routes/_authenticated/vendedor.pedido-assistido'
import { Route as ApiPublicLoginRouteImport } from './routes/api/public/login'
import { Route as AuthenticatedAdminEcossistemaIndexRouteImport } from './routes/_authenticated/admin.ecossistema.index'
import { Route as AuthenticatedAdminEcossistemaSlugRouteImport } from './routes/_authenticated/admin.ecossistema.$slug'
import { Route as AuthenticatedAdminEcossistemaBlingRouteImport } from './routes/_authenticated/admin.ecossistema.bling'
import { Route as AuthenticatedAdminNfeImportacaoIndexRouteImport } from './routes/_authenticated/admin.nfe-importacao.index'
import { Route as AuthenticatedAdminNfeImportacaoIdRouteImport } from './routes/_authenticated/admin.nfe-importacao.$id'
import { Route as AuthenticatedAdminPedidosCompraIndexRouteImport } from './routes/_authenticated/admin.pedidos-compra.index'
import { Route as AuthenticatedAdminPedidosCompraIdRouteImport } from './routes/_authenticated/admin.pedidos-compra.$id'
import { Route as AuthenticatedAdminPedidosCompraNovoRouteImport } from './routes/_authenticated/admin.pedidos-compra.novo'
import { Route as AuthenticatedAdminPedidosIdRouteImport } from './routes/_authenticated/admin.pedidos.$id'
import { Route as AuthenticatedAdminProdutosIndexRouteImport } from './routes/_authenticated/admin.produtos.index'
import { Route as AuthenticatedAdminProdutosIdRouteImport } from './routes/_authenticated/admin.produtos.$id'
import { Route as AuthenticatedAdminProdutosNovoRouteImport } from './routes/_authenticated/admin.produtos.novo'
import { Route as AuthenticatedAdminRecebimentosIndexRouteImport } from './routes/_authenticated/admin.recebimentos.index'
import { Route as AuthenticatedAdminRecebimentosIdRouteImport } from './routes/_authenticated/admin.recebimentos.$id'
import { Route as AuthenticatedAdminSaneamentoAliasesRouteImport } from './routes/_authenticated/admin.saneamento.aliases'
import { Route as AuthenticatedAdminVendedoresNovoRouteImport } from './routes/_authenticated/admin.vendedores.novo'
import { Route as ApiPublicBlingCallbackRouteImport } from './routes/api/public/bling.callback'
import { Route as AuthenticatedAdminPedidosCompraEditarIdRouteImport } from './routes/_authenticated/admin.pedidos-compra.editar.$id'
import { Route as ApiPublicStoneConciliationWebhookRouteImport } from './routes/api/public/stone.conciliation.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivacaoRoute = AtivacaoRouteImport.update({
  id: '/ativacao',
  path: '/ativacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendedorRoute = AuthenticatedVendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSocialDotwebpRoute = BrandSocialDotwebpRouteImport.update({
  id: '/brand/social.webp',
  path: '/brand/social.webp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlingRoute = AuthenticatedAdminBlingRouteImport.update({
  id: '/bling',
  path: '/bling',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCadastrosB2bRoute =
  AuthenticatedAdminCadastrosB2bRouteImport.update({
    id: '/cadastros-b2b',
    path: '/cadastros-b2b',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCatalogoFabricantesRoute =
  AuthenticatedAdminCatalogoFabricantesRouteImport.update({
    id: '/catalogo-fabricantes',
    path: '/catalogo-fabricantes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/cupons',
    path: '/cupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEcossistemaRoute =
  AuthenticatedAdminEcossistemaRouteImport.update({
    id: '/ecossistema',
    path: '/ecossistema',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnriquecimentoProdutosRoute =
  AuthenticatedAdminEnriquecimentoProdutosRouteImport.update({
    id: '/enriquecimento-produtos',
    path: '/enriquecimento-produtos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEstoqueRoute =
  AuthenticatedAdminEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExpedicaoRoute =
  AuthenticatedAdminExpedicaoRouteImport.update({
    id: '/expedicao',
    path: '/expedicao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFiliaisRoute =
  AuthenticatedAdminFiliaisRouteImport.update({
    id: '/filiais',
    path: '/filiais',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFiscalRoute =
  AuthenticatedAdminFiscalRouteImport.update({
    id: '/fiscal',
    path: '/fiscal',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFiscalProdutosRoute =
  AuthenticatedAdminFiscalProdutosRouteImport.update({
    id: '/fiscal-produtos',
    path: '/fiscal-produtos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFornecedoresRoute =
  AuthenticatedAdminFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHistoricoCustosRoute =
  AuthenticatedAdminHistoricoCustosRouteImport.update({
    id: '/historico-custos',
    path: '/historico-custos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHomologacaoRoute =
  AuthenticatedAdminHomologacaoRouteImport.update({
    id: '/homologacao',
    path: '/homologacao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIaAesBusinessRoute =
  AuthenticatedAdminIaAesBusinessRouteImport.update({
    id: '/ia-aes-business',
    path: '/ia-aes-business',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInteligenciaComercialRoute =
  AuthenticatedAdminInteligenciaComercialRouteImport.update({
    id: '/inteligencia-comercial',
    path: '/inteligencia-comercial',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarcasRoute =
  AuthenticatedAdminMarcasRouteImport.update({
    id: '/marcas',
    path: '/marcas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMigracaoBlingRoute =
  AuthenticatedAdminMigracaoBlingRouteImport.update({
    id: '/migracao-bling',
    path: '/migracao-bling',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrcamentosRoute =
  AuthenticatedAdminOrcamentosRouteImport.update({
    id: '/orcamentos',
    path: '/orcamentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPdvRoute = AuthenticatedAdminPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromocoesRoute =
  AuthenticatedAdminPromocoesRouteImport.update({
    id: '/promocoes',
    path: '/promocoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReposicaoRoute =
  AuthenticatedAdminReposicaoRouteImport.update({
    id: '/reposicao',
    path: '/reposicao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRevisaoCodigosRoute =
  AuthenticatedAdminRevisaoCodigosRouteImport.update({
    id: '/revisao-codigos',
    path: '/revisao-codigos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSaneamentoRoute =
  AuthenticatedAdminSaneamentoRouteImport.update({
    id: '/saneamento',
    path: '/saneamento',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSaneamentoCustosRoute =
  AuthenticatedAdminSaneamentoCustosRouteImport.update({
    id: '/saneamento-custos',
    path: '/saneamento-custos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSuprimentosRoute =
  AuthenticatedAdminSuprimentosRouteImport.update({
    id: '/suprimentos',
    path: '/suprimentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVendedoresRoute =
  AuthenticatedAdminVendedoresRouteImport.update({
    id: '/vendedores',
    path: '/vendedores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedVendedorIndexRoute =
  AuthenticatedVendedorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedVendedorClientesRoute =
  AuthenticatedVendedorClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedVendedorMeusPedidosRoute =
  AuthenticatedVendedorMeusPedidosRouteImport.update({
    id: '/meus-pedidos',
    path: '/meus-pedidos',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedVendedorPedidoAssistidoRoute =
  AuthenticatedVendedorPedidoAssistidoRouteImport.update({
    id: '/pedido-assistido',
    path: '/pedido-assistido',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const ApiPublicLoginRoute = ApiPublicLoginRouteImport.update({
  id: '/api/public/login',
  path: '/api/public/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminEcossistemaIndexRoute =
  AuthenticatedAdminEcossistemaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEcossistemaRoute,
  } as any)
const AuthenticatedAdminEcossistemaSlugRoute =
  AuthenticatedAdminEcossistemaSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAdminEcossistemaRoute,
  } as any)
const AuthenticatedAdminEcossistemaBlingRoute =
  AuthenticatedAdminEcossistemaBlingRouteImport.update({
    id: '/bling',
    path: '/bling',
    getParentRoute: () => AuthenticatedAdminEcossistemaRoute,
  } as any)
const AuthenticatedAdminNfeImportacaoIndexRoute =
  AuthenticatedAdminNfeImportacaoIndexRouteImport.update({
    id: '/nfe-importacao/',
    path: '/nfe-importacao/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNfeImportacaoIdRoute =
  AuthenticatedAdminNfeImportacaoIdRouteImport.update({
    id: '/nfe-importacao/$id',
    path: '/nfe-importacao/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosCompraIndexRoute =
  AuthenticatedAdminPedidosCompraIndexRouteImport.update({
    id: '/pedidos-compra/',
    path: '/pedidos-compra/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosCompraIdRoute =
  AuthenticatedAdminPedidosCompraIdRouteImport.update({
    id: '/pedidos-compra/$id',
    path: '/pedidos-compra/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosCompraNovoRoute =
  AuthenticatedAdminPedidosCompraNovoRouteImport.update({
    id: '/pedidos-compra/novo',
    path: '/pedidos-compra/novo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosIdRoute =
  AuthenticatedAdminPedidosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPedidosRoute,
  } as any)
const AuthenticatedAdminProdutosIndexRoute =
  AuthenticatedAdminProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProdutosIdRoute =
  AuthenticatedAdminProdutosIdRouteImport.update({
    id: '/produtos/$id',
    path: '/produtos/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProdutosNovoRoute =
  AuthenticatedAdminProdutosNovoRouteImport.update({
    id: '/produtos/novo',
    path: '/produtos/novo',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRecebimentosIndexRoute =
  AuthenticatedAdminRecebimentosIndexRouteImport.update({
    id: '/recebimentos/',
    path: '/recebimentos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRecebimentosIdRoute =
  AuthenticatedAdminRecebimentosIdRouteImport.update({
    id: '/recebimentos/$id',
    path: '/recebimentos/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSaneamentoAliasesRoute =
  AuthenticatedAdminSaneamentoAliasesRouteImport.update({
    id: '/aliases',
    path: '/aliases',
    getParentRoute: () => AuthenticatedAdminSaneamentoRoute,
  } as any)
const AuthenticatedAdminVendedoresNovoRoute =
  AuthenticatedAdminVendedoresNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedAdminVendedoresRoute,
  } as any)
const ApiPublicBlingCallbackRoute = ApiPublicBlingCallbackRouteImport.update({
  id: '/api/public/bling/callback',
  path: '/api/public/bling/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPedidosCompraEditarIdRoute =
  AuthenticatedAdminPedidosCompraEditarIdRouteImport.update({
    id: '/pedidos-compra/editar/$id',
    path: '/pedidos-compra/editar/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicStoneConciliationWebhookRoute =
  ApiPublicStoneConciliationWebhookRouteImport.update({
    id: '/api/public/stone/conciliation/webhook',
    path: '/api/public/stone/conciliation/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ativacao': typeof AtivacaoRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/mcp': typeof McpRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/conta': typeof AuthenticatedContaRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/vendedor': typeof AuthenticatedVendedorRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/brand/social.webp': typeof BrandSocialDotwebpRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/bling': typeof AuthenticatedAdminBlingRoute
  '/admin/cadastros-b2b': typeof AuthenticatedAdminCadastrosB2bRoute
  '/admin/catalogo-fabricantes': typeof AuthenticatedAdminCatalogoFabricantesRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/ecossistema': typeof AuthenticatedAdminEcossistemaRouteWithChildren
  '/admin/enriquecimento-produtos': typeof AuthenticatedAdminEnriquecimentoProdutosRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/expedicao': typeof AuthenticatedAdminExpedicaoRoute
  '/admin/filiais': typeof AuthenticatedAdminFiliaisRoute
  '/admin/fiscal': typeof AuthenticatedAdminFiscalRoute
  '/admin/fiscal-produtos': typeof AuthenticatedAdminFiscalProdutosRoute
  '/admin/fornecedores': typeof AuthenticatedAdminFornecedoresRoute
  '/admin/historico-custos': typeof AuthenticatedAdminHistoricoCustosRoute
  '/admin/homologacao': typeof AuthenticatedAdminHomologacaoRoute
  '/admin/ia-aes-business': typeof AuthenticatedAdminIaAesBusinessRoute
  '/admin/inteligencia-comercial': typeof AuthenticatedAdminInteligenciaComercialRoute
  '/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/admin/migracao-bling': typeof AuthenticatedAdminMigracaoBlingRoute
  '/admin/orcamentos': typeof AuthenticatedAdminOrcamentosRoute
  '/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/admin/promocoes': typeof AuthenticatedAdminPromocoesRoute
  '/admin/reposicao': typeof AuthenticatedAdminReposicaoRoute
  '/admin/revisao-codigos': typeof AuthenticatedAdminRevisaoCodigosRoute
  '/admin/saneamento': typeof AuthenticatedAdminSaneamentoRouteWithChildren
  '/admin/saneamento-custos': typeof AuthenticatedAdminSaneamentoCustosRoute
  '/admin/suprimentos': typeof AuthenticatedAdminSuprimentosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRouteWithChildren
  '/vendedor/clientes': typeof AuthenticatedVendedorClientesRoute
  '/vendedor/meus-pedidos': typeof AuthenticatedVendedorMeusPedidosRoute
  '/vendedor/pedido-assistido': typeof AuthenticatedVendedorPedidoAssistidoRoute
  '/api/public/login': typeof ApiPublicLoginRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/vendedor/': typeof AuthenticatedVendedorIndexRoute
  '/admin/ecossistema/$slug': typeof AuthenticatedAdminEcossistemaSlugRoute
  '/admin/ecossistema/bling': typeof AuthenticatedAdminEcossistemaBlingRoute
  '/admin/nfe-importacao/$id': typeof AuthenticatedAdminNfeImportacaoIdRoute
  '/admin/pedidos-compra/$id': typeof AuthenticatedAdminPedidosCompraIdRoute
  '/admin/pedidos-compra/novo': typeof AuthenticatedAdminPedidosCompraNovoRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/admin/produtos/novo': typeof AuthenticatedAdminProdutosNovoRoute
  '/admin/recebimentos/$id': typeof AuthenticatedAdminRecebimentosIdRoute
  '/admin/saneamento/aliases': typeof AuthenticatedAdminSaneamentoAliasesRoute
  '/admin/vendedores/novo': typeof AuthenticatedAdminVendedoresNovoRoute
  '/api/public/bling/callback': typeof ApiPublicBlingCallbackRoute
  '/admin/ecossistema/': typeof AuthenticatedAdminEcossistemaIndexRoute
  '/admin/nfe-importacao/': typeof AuthenticatedAdminNfeImportacaoIndexRoute
  '/admin/pedidos-compra/': typeof AuthenticatedAdminPedidosCompraIndexRoute
  '/admin/produtos/': typeof AuthenticatedAdminProdutosIndexRoute
  '/admin/recebimentos/': typeof AuthenticatedAdminRecebimentosIndexRoute
  '/admin/pedidos-compra/editar/$id': typeof AuthenticatedAdminPedidosCompraEditarIdRoute
  '/api/public/stone/conciliation/webhook': typeof ApiPublicStoneConciliationWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativacao': typeof AtivacaoRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/mcp': typeof McpRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/conta': typeof AuthenticatedContaRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/api/health': typeof ApiHealthRoute
  '/brand/social.webp': typeof BrandSocialDotwebpRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/bling': typeof AuthenticatedAdminBlingRoute
  '/admin/cadastros-b2b': typeof AuthenticatedAdminCadastrosB2bRoute
  '/admin/catalogo-fabricantes': typeof AuthenticatedAdminCatalogoFabricantesRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/enriquecimento-produtos': typeof AuthenticatedAdminEnriquecimentoProdutosRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/expedicao': typeof AuthenticatedAdminExpedicaoRoute
  '/admin/filiais': typeof AuthenticatedAdminFiliaisRoute
  '/admin/fiscal': typeof AuthenticatedAdminFiscalRoute
  '/admin/fiscal-produtos': typeof AuthenticatedAdminFiscalProdutosRoute
  '/admin/fornecedores': typeof AuthenticatedAdminFornecedoresRoute
  '/admin/historico-custos': typeof AuthenticatedAdminHistoricoCustosRoute
  '/admin/homologacao': typeof AuthenticatedAdminHomologacaoRoute
  '/admin/ia-aes-business': typeof AuthenticatedAdminIaAesBusinessRoute
  '/admin/inteligencia-comercial': typeof AuthenticatedAdminInteligenciaComercialRoute
  '/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/admin/migracao-bling': typeof AuthenticatedAdminMigracaoBlingRoute
  '/admin/orcamentos': typeof AuthenticatedAdminOrcamentosRoute
  '/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/admin/promocoes': typeof AuthenticatedAdminPromocoesRoute
  '/admin/reposicao': typeof AuthenticatedAdminReposicaoRoute
  '/admin/revisao-codigos': typeof AuthenticatedAdminRevisaoCodigosRoute
  '/admin/saneamento': typeof AuthenticatedAdminSaneamentoRouteWithChildren
  '/admin/saneamento-custos': typeof AuthenticatedAdminSaneamentoCustosRoute
  '/admin/suprimentos': typeof AuthenticatedAdminSuprimentosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRouteWithChildren
  '/vendedor/clientes': typeof AuthenticatedVendedorClientesRoute
  '/vendedor/meus-pedidos': typeof AuthenticatedVendedorMeusPedidosRoute
  '/vendedor/pedido-assistido': typeof AuthenticatedVendedorPedidoAssistidoRoute
  '/api/public/login': typeof ApiPublicLoginRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/vendedor': typeof AuthenticatedVendedorIndexRoute
  '/admin/ecossistema/$slug': typeof AuthenticatedAdminEcossistemaSlugRoute
  '/admin/ecossistema/bling': typeof AuthenticatedAdminEcossistemaBlingRoute
  '/admin/nfe-importacao/$id': typeof AuthenticatedAdminNfeImportacaoIdRoute
  '/admin/pedidos-compra/$id': typeof AuthenticatedAdminPedidosCompraIdRoute
  '/admin/pedidos-compra/novo': typeof AuthenticatedAdminPedidosCompraNovoRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/admin/produtos/novo': typeof AuthenticatedAdminProdutosNovoRoute
  '/admin/recebimentos/$id': typeof AuthenticatedAdminRecebimentosIdRoute
  '/admin/saneamento/aliases': typeof AuthenticatedAdminSaneamentoAliasesRoute
  '/admin/vendedores/novo': typeof AuthenticatedAdminVendedoresNovoRoute
  '/api/public/bling/callback': typeof ApiPublicBlingCallbackRoute
  '/admin/ecossistema': typeof AuthenticatedAdminEcossistemaIndexRoute
  '/admin/nfe-importacao': typeof AuthenticatedAdminNfeImportacaoIndexRoute
  '/admin/pedidos-compra': typeof AuthenticatedAdminPedidosCompraIndexRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosIndexRoute
  '/admin/recebimentos': typeof AuthenticatedAdminRecebimentosIndexRoute
  '/admin/pedidos-compra/editar/$id': typeof AuthenticatedAdminPedidosCompraEditarIdRoute
  '/api/public/stone/conciliation/webhook': typeof ApiPublicStoneConciliationWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ativacao': typeof AtivacaoRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/mcp': typeof McpRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/vendedor': typeof AuthenticatedVendedorRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/brand/social.webp': typeof BrandSocialDotwebpRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/bling': typeof AuthenticatedAdminBlingRoute
  '/_authenticated/admin/cadastros-b2b': typeof AuthenticatedAdminCadastrosB2bRoute
  '/_authenticated/admin/catalogo-fabricantes': typeof AuthenticatedAdminCatalogoFabricantesRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/ecossistema': typeof AuthenticatedAdminEcossistemaRouteWithChildren
  '/_authenticated/admin/enriquecimento-produtos': typeof AuthenticatedAdminEnriquecimentoProdutosRoute
  '/_authenticated/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/_authenticated/admin/expedicao': typeof AuthenticatedAdminExpedicaoRoute
  '/_authenticated/admin/filiais': typeof AuthenticatedAdminFiliaisRoute
  '/_authenticated/admin/fiscal': typeof AuthenticatedAdminFiscalRoute
  '/_authenticated/admin/fiscal-produtos': typeof AuthenticatedAdminFiscalProdutosRoute
  '/_authenticated/admin/fornecedores': typeof AuthenticatedAdminFornecedoresRoute
  '/_authenticated/admin/historico-custos': typeof AuthenticatedAdminHistoricoCustosRoute
  '/_authenticated/admin/homologacao': typeof AuthenticatedAdminHomologacaoRoute
  '/_authenticated/admin/ia-aes-business': typeof AuthenticatedAdminIaAesBusinessRoute
  '/_authenticated/admin/inteligencia-comercial': typeof AuthenticatedAdminInteligenciaComercialRoute
  '/_authenticated/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/_authenticated/admin/migracao-bling': typeof AuthenticatedAdminMigracaoBlingRoute
  '/_authenticated/admin/orcamentos': typeof AuthenticatedAdminOrcamentosRoute
  '/_authenticated/admin/pdv': typeof AuthenticatedAdminPdvRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/_authenticated/admin/promocoes': typeof AuthenticatedAdminPromocoesRoute
  '/_authenticated/admin/reposicao': typeof AuthenticatedAdminReposicaoRoute
  '/_authenticated/admin/revisao-codigos': typeof AuthenticatedAdminRevisaoCodigosRoute
  '/_authenticated/admin/saneamento': typeof AuthenticatedAdminSaneamentoRouteWithChildren
  '/_authenticated/admin/saneamento-custos': typeof AuthenticatedAdminSaneamentoCustosRoute
  '/_authenticated/admin/suprimentos': typeof AuthenticatedAdminSuprimentosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/vendedores': typeof AuthenticatedAdminVendedoresRouteWithChildren
  '/_authenticated/vendedor/clientes': typeof AuthenticatedVendedorClientesRoute
  '/_authenticated/vendedor/meus-pedidos': typeof AuthenticatedVendedorMeusPedidosRoute
  '/_authenticated/vendedor/pedido-assistido': typeof AuthenticatedVendedorPedidoAssistidoRoute
  '/api/public/login': typeof ApiPublicLoginRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/vendedor/': typeof AuthenticatedVendedorIndexRoute
  '/_authenticated/admin/ecossistema/$slug': typeof AuthenticatedAdminEcossistemaSlugRoute
  '/_authenticated/admin/ecossistema/bling': typeof AuthenticatedAdminEcossistemaBlingRoute
  '/_authenticated/admin/nfe-importacao/$id': typeof AuthenticatedAdminNfeImportacaoIdRoute
  '/_authenticated/admin/pedidos-compra/$id': typeof AuthenticatedAdminPedidosCompraIdRoute
  '/_authenticated/admin/pedidos-compra/novo': typeof AuthenticatedAdminPedidosCompraNovoRoute
  '/_authenticated/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/_authenticated/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/_authenticated/admin/produtos/novo': typeof AuthenticatedAdminProdutosNovoRoute
  '/_authenticated/admin/recebimentos/$id': typeof AuthenticatedAdminRecebimentosIdRoute
  '/_authenticated/admin/saneamento/aliases': typeof AuthenticatedAdminSaneamentoAliasesRoute
  '/_authenticated/admin/vendedores/novo': typeof AuthenticatedAdminVendedoresNovoRoute
  '/api/public/bling/callback': typeof ApiPublicBlingCallbackRoute
  '/_authenticated/admin/ecossistema/': typeof AuthenticatedAdminEcossistemaIndexRoute
  '/_authenticated/admin/nfe-importacao/': typeof AuthenticatedAdminNfeImportacaoIndexRoute
  '/_authenticated/admin/pedidos-compra/': typeof AuthenticatedAdminPedidosCompraIndexRoute
  '/_authenticated/admin/produtos/': typeof AuthenticatedAdminProdutosIndexRoute
  '/_authenticated/admin/recebimentos/': typeof AuthenticatedAdminRecebimentosIndexRoute
  '/_authenticated/admin/pedidos-compra/editar/$id': typeof AuthenticatedAdminPedidosCompraEditarIdRoute
  '/api/public/stone/conciliation/webhook': typeof ApiPublicStoneConciliationWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ativacao'
    | '/auth'
    | '/b2b'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/esqueci-senha'
    | '/mcp'
    | '/primeiro-acesso'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/conta'
    | '/pedidos'
    | '/vendedor'
    | '/api/health'
    | '/brand/social.webp'
    | '/produto/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/auditoria'
    | '/admin/banners'
    | '/admin/bling'
    | '/admin/cadastros-b2b'
    | '/admin/catalogo-fabricantes'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/ecossistema'
    | '/admin/enriquecimento-produtos'
    | '/admin/estoque'
    | '/admin/expedicao'
    | '/admin/filiais'
    | '/admin/fiscal'
    | '/admin/fiscal-produtos'
    | '/admin/fornecedores'
    | '/admin/historico-custos'
    | '/admin/homologacao'
    | '/admin/ia-aes-business'
    | '/admin/inteligencia-comercial'
    | '/admin/marcas'
    | '/admin/migracao-bling'
    | '/admin/orcamentos'
    | '/admin/pdv'
    | '/admin/pedidos'
    | '/admin/promocoes'
    | '/admin/reposicao'
    | '/admin/revisao-codigos'
    | '/admin/saneamento'
    | '/admin/saneamento-custos'
    | '/admin/suprimentos'
    | '/admin/usuarios'
    | '/admin/vendedores'
    | '/vendedor/clientes'
    | '/vendedor/meus-pedidos'
    | '/vendedor/pedido-assistido'
    | '/api/public/login'
    | '/admin/'
    | '/vendedor/'
    | '/admin/ecossistema/$slug'
    | '/admin/ecossistema/bling'
    | '/admin/nfe-importacao/$id'
    | '/admin/pedidos-compra/$id'
    | '/admin/pedidos-compra/novo'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/recebimentos/$id'
    | '/admin/saneamento/aliases'
    | '/admin/vendedores/novo'
    | '/api/public/bling/callback'
    | '/admin/ecossistema/'
    | '/admin/nfe-importacao/'
    | '/admin/pedidos-compra/'
    | '/admin/produtos/'
    | '/admin/recebimentos/'
    | '/admin/pedidos-compra/editar/$id'
    | '/api/public/stone/conciliation/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativacao'
    | '/auth'
    | '/b2b'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/esqueci-senha'
    | '/mcp'
    | '/primeiro-acesso'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/conta'
    | '/pedidos'
    | '/api/health'
    | '/brand/social.webp'
    | '/produto/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/auditoria'
    | '/admin/banners'
    | '/admin/bling'
    | '/admin/cadastros-b2b'
    | '/admin/catalogo-fabricantes'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/enriquecimento-produtos'
    | '/admin/estoque'
    | '/admin/expedicao'
    | '/admin/filiais'
    | '/admin/fiscal'
    | '/admin/fiscal-produtos'
    | '/admin/fornecedores'
    | '/admin/historico-custos'
    | '/admin/homologacao'
    | '/admin/ia-aes-business'
    | '/admin/inteligencia-comercial'
    | '/admin/marcas'
    | '/admin/migracao-bling'
    | '/admin/orcamentos'
    | '/admin/pdv'
    | '/admin/pedidos'
    | '/admin/promocoes'
    | '/admin/reposicao'
    | '/admin/revisao-codigos'
    | '/admin/saneamento'
    | '/admin/saneamento-custos'
    | '/admin/suprimentos'
    | '/admin/usuarios'
    | '/admin/vendedores'
    | '/vendedor/clientes'
    | '/vendedor/meus-pedidos'
    | '/vendedor/pedido-assistido'
    | '/api/public/login'
    | '/admin'
    | '/vendedor'
    | '/admin/ecossistema/$slug'
    | '/admin/ecossistema/bling'
    | '/admin/nfe-importacao/$id'
    | '/admin/pedidos-compra/$id'
    | '/admin/pedidos-compra/novo'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/recebimentos/$id'
    | '/admin/saneamento/aliases'
    | '/admin/vendedores/novo'
    | '/api/public/bling/callback'
    | '/admin/ecossistema'
    | '/admin/nfe-importacao'
    | '/admin/pedidos-compra'
    | '/admin/produtos'
    | '/admin/recebimentos'
    | '/admin/pedidos-compra/editar/$id'
    | '/api/public/stone/conciliation/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ativacao'
    | '/auth'
    | '/b2b'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/esqueci-senha'
    | '/mcp'
    | '/primeiro-acesso'
    | '/redefinir-senha'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/conta'
    | '/_authenticated/pedidos'
    | '/_authenticated/vendedor'
    | '/api/health'
    | '/brand/social.webp'
    | '/produto/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/bling'
    | '/_authenticated/admin/cadastros-b2b'
    | '/_authenticated/admin/catalogo-fabricantes'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/ecossistema'
    | '/_authenticated/admin/enriquecimento-produtos'
    | '/_authenticated/admin/estoque'
    | '/_authenticated/admin/expedicao'
    | '/_authenticated/admin/filiais'
    | '/_authenticated/admin/fiscal'
    | '/_authenticated/admin/fiscal-produtos'
    | '/_authenticated/admin/fornecedores'
    | '/_authenticated/admin/historico-custos'
    | '/_authenticated/admin/homologacao'
    | '/_authenticated/admin/ia-aes-business'
    | '/_authenticated/admin/inteligencia-comercial'
    | '/_authenticated/admin/marcas'
    | '/_authenticated/admin/migracao-bling'
    | '/_authenticated/admin/orcamentos'
    | '/_authenticated/admin/pdv'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/promocoes'
    | '/_authenticated/admin/reposicao'
    | '/_authenticated/admin/revisao-codigos'
    | '/_authenticated/admin/saneamento'
    | '/_authenticated/admin/saneamento-custos'
    | '/_authenticated/admin/suprimentos'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/vendedores'
    | '/_authenticated/vendedor/clientes'
    | '/_authenticated/vendedor/meus-pedidos'
    | '/_authenticated/vendedor/pedido-assistido'
    | '/api/public/login'
    | '/_authenticated/admin/'
    | '/_authenticated/vendedor/'
    | '/_authenticated/admin/ecossistema/$slug'
    | '/_authenticated/admin/ecossistema/bling'
    | '/_authenticated/admin/nfe-importacao/$id'
    | '/_authenticated/admin/pedidos-compra/$id'
    | '/_authenticated/admin/pedidos-compra/novo'
    | '/_authenticated/admin/pedidos/$id'
    | '/_authenticated/admin/produtos/$id'
    | '/_authenticated/admin/produtos/novo'
    | '/_authenticated/admin/recebimentos/$id'
    | '/_authenticated/admin/saneamento/aliases'
    | '/_authenticated/admin/vendedores/novo'
    | '/api/public/bling/callback'
    | '/_authenticated/admin/ecossistema/'
    | '/_authenticated/admin/nfe-importacao/'
    | '/_authenticated/admin/pedidos-compra/'
    | '/_authenticated/admin/produtos/'
    | '/_authenticated/admin/recebimentos/'
    | '/_authenticated/admin/pedidos-compra/editar/$id'
    | '/api/public/stone/conciliation/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AtivacaoRoute: typeof AtivacaoRoute
  AuthRoute: typeof AuthRoute
  B2bRoute: typeof B2bRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  McpRoute: typeof McpRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BrandSocialDotwebpRoute: typeof BrandSocialDotwebpRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicLoginRoute: typeof ApiPublicLoginRoute
  ApiPublicBlingCallbackRoute: typeof ApiPublicBlingCallbackRoute
  ApiPublicStoneConciliationWebhookRoute: typeof ApiPublicStoneConciliationWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativacao': {
      id: '/ativacao'
      path: '/ativacao'
      fullPath: '/ativacao'
      preLoaderRoute: typeof AtivacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendedor': {
      id: '/_authenticated/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof AuthenticatedVendedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/social.webp': {
      id: '/brand/social.webp'
      path: '/brand/social.webp'
      fullPath: '/brand/social.webp'
      preLoaderRoute: typeof BrandSocialDotwebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bling': {
      id: '/_authenticated/admin/bling'
      path: '/bling'
      fullPath: '/admin/bling'
      preLoaderRoute: typeof AuthenticatedAdminBlingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cadastros-b2b': {
      id: '/_authenticated/admin/cadastros-b2b'
      path: '/cadastros-b2b'
      fullPath: '/admin/cadastros-b2b'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosB2bRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/catalogo-fabricantes': {
      id: '/_authenticated/admin/catalogo-fabricantes'
      path: '/catalogo-fabricantes'
      fullPath: '/admin/catalogo-fabricantes'
      preLoaderRoute: typeof AuthenticatedAdminCatalogoFabricantesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ecossistema': {
      id: '/_authenticated/admin/ecossistema'
      path: '/ecossistema'
      fullPath: '/admin/ecossistema'
      preLoaderRoute: typeof AuthenticatedAdminEcossistemaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enriquecimento-produtos': {
      id: '/_authenticated/admin/enriquecimento-produtos'
      path: '/enriquecimento-produtos'
      fullPath: '/admin/enriquecimento-produtos'
      preLoaderRoute: typeof AuthenticatedAdminEnriquecimentoProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/estoque': {
      id: '/_authenticated/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AuthenticatedAdminEstoqueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/expedicao': {
      id: '/_authenticated/admin/expedicao'
      path: '/expedicao'
      fullPath: '/admin/expedicao'
      preLoaderRoute: typeof AuthenticatedAdminExpedicaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/filiais': {
      id: '/_authenticated/admin/filiais'
      path: '/filiais'
      fullPath: '/admin/filiais'
      preLoaderRoute: typeof AuthenticatedAdminFiliaisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fiscal': {
      id: '/_authenticated/admin/fiscal'
      path: '/fiscal'
      fullPath: '/admin/fiscal'
      preLoaderRoute: typeof AuthenticatedAdminFiscalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fiscal-produtos': {
      id: '/_authenticated/admin/fiscal-produtos'
      path: '/fiscal-produtos'
      fullPath: '/admin/fiscal-produtos'
      preLoaderRoute: typeof AuthenticatedAdminFiscalProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fornecedores': {
      id: '/_authenticated/admin/fornecedores'
      path: '/fornecedores'
      fullPath: '/admin/fornecedores'
      preLoaderRoute: typeof AuthenticatedAdminFornecedoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/historico-custos': {
      id: '/_authenticated/admin/historico-custos'
      path: '/historico-custos'
      fullPath: '/admin/historico-custos'
      preLoaderRoute: typeof AuthenticatedAdminHistoricoCustosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/homologacao': {
      id: '/_authenticated/admin/homologacao'
      path: '/homologacao'
      fullPath: '/admin/homologacao'
      preLoaderRoute: typeof AuthenticatedAdminHomologacaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ia-aes-business': {
      id: '/_authenticated/admin/ia-aes-business'
      path: '/ia-aes-business'
      fullPath: '/admin/ia-aes-business'
      preLoaderRoute: typeof AuthenticatedAdminIaAesBusinessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inteligencia-comercial': {
      id: '/_authenticated/admin/inteligencia-comercial'
      path: '/inteligencia-comercial'
      fullPath: '/admin/inteligencia-comercial'
      preLoaderRoute: typeof AuthenticatedAdminInteligenciaComercialRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marcas': {
      id: '/_authenticated/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AuthenticatedAdminMarcasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/migracao-bling': {
      id: '/_authenticated/admin/migracao-bling'
      path: '/migracao-bling'
      fullPath: '/admin/migracao-bling'
      preLoaderRoute: typeof AuthenticatedAdminMigracaoBlingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orcamentos': {
      id: '/_authenticated/admin/orcamentos'
      path: '/orcamentos'
      fullPath: '/admin/orcamentos'
      preLoaderRoute: typeof AuthenticatedAdminOrcamentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pdv': {
      id: '/_authenticated/admin/pdv'
      path: '/pdv'
      fullPath: '/admin/pdv'
      preLoaderRoute: typeof AuthenticatedAdminPdvRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promocoes': {
      id: '/_authenticated/admin/promocoes'
      path: '/promocoes'
      fullPath: '/admin/promocoes'
      preLoaderRoute: typeof AuthenticatedAdminPromocoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reposicao': {
      id: '/_authenticated/admin/reposicao'
      path: '/reposicao'
      fullPath: '/admin/reposicao'
      preLoaderRoute: typeof AuthenticatedAdminReposicaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/revisao-codigos': {
      id: '/_authenticated/admin/revisao-codigos'
      path: '/revisao-codigos'
      fullPath: '/admin/revisao-codigos'
      preLoaderRoute: typeof AuthenticatedAdminRevisaoCodigosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/saneamento': {
      id: '/_authenticated/admin/saneamento'
      path: '/saneamento'
      fullPath: '/admin/saneamento'
      preLoaderRoute: typeof AuthenticatedAdminSaneamentoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/saneamento-custos': {
      id: '/_authenticated/admin/saneamento-custos'
      path: '/saneamento-custos'
      fullPath: '/admin/saneamento-custos'
      preLoaderRoute: typeof AuthenticatedAdminSaneamentoCustosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/suprimentos': {
      id: '/_authenticated/admin/suprimentos'
      path: '/suprimentos'
      fullPath: '/admin/suprimentos'
      preLoaderRoute: typeof AuthenticatedAdminSuprimentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vendedores': {
      id: '/_authenticated/admin/vendedores'
      path: '/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AuthenticatedAdminVendedoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/vendedor/': {
      id: '/_authenticated/vendedor/'
      path: '/'
      fullPath: '/vendedor/'
      preLoaderRoute: typeof AuthenticatedVendedorIndexRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/vendedor/clientes': {
      id: '/_authenticated/vendedor/clientes'
      path: '/clientes'
      fullPath: '/vendedor/clientes'
      preLoaderRoute: typeof AuthenticatedVendedorClientesRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/vendedor/meus-pedidos': {
      id: '/_authenticated/vendedor/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/vendedor/meus-pedidos'
      preLoaderRoute: typeof AuthenticatedVendedorMeusPedidosRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/vendedor/pedido-assistido': {
      id: '/_authenticated/vendedor/pedido-assistido'
      path: '/pedido-assistido'
      fullPath: '/vendedor/pedido-assistido'
      preLoaderRoute: typeof AuthenticatedVendedorPedidoAssistidoRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/api/public/login': {
      id: '/api/public/login'
      path: '/api/public/login'
      fullPath: '/api/public/login'
      preLoaderRoute: typeof ApiPublicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/ecossistema/': {
      id: '/_authenticated/admin/ecossistema/'
      path: '/'
      fullPath: '/admin/ecossistema/'
      preLoaderRoute: typeof AuthenticatedAdminEcossistemaIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEcossistemaRoute
    }
    '/_authenticated/admin/ecossistema/$slug': {
      id: '/_authenticated/admin/ecossistema/$slug'
      path: '/$slug'
      fullPath: '/admin/ecossistema/$slug'
      preLoaderRoute: typeof AuthenticatedAdminEcossistemaSlugRouteImport
      parentRoute: typeof AuthenticatedAdminEcossistemaRoute
    }
    '/_authenticated/admin/ecossistema/bling': {
      id: '/_authenticated/admin/ecossistema/bling'
      path: '/bling'
      fullPath: '/admin/ecossistema/bling'
      preLoaderRoute: typeof AuthenticatedAdminEcossistemaBlingRouteImport
      parentRoute: typeof AuthenticatedAdminEcossistemaRoute
    }
    '/_authenticated/admin/nfe-importacao/': {
      id: '/_authenticated/admin/nfe-importacao/'
      path: '/nfe-importacao'
      fullPath: '/admin/nfe-importacao/'
      preLoaderRoute: typeof AuthenticatedAdminNfeImportacaoIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/nfe-importacao/$id': {
      id: '/_authenticated/admin/nfe-importacao/$id'
      path: '/nfe-importacao/$id'
      fullPath: '/admin/nfe-importacao/$id'
      preLoaderRoute: typeof AuthenticatedAdminNfeImportacaoIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos-compra/': {
      id: '/_authenticated/admin/pedidos-compra/'
      path: '/pedidos-compra'
      fullPath: '/admin/pedidos-compra/'
      preLoaderRoute: typeof AuthenticatedAdminPedidosCompraIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos-compra/$id': {
      id: '/_authenticated/admin/pedidos-compra/$id'
      path: '/pedidos-compra/$id'
      fullPath: '/admin/pedidos-compra/$id'
      preLoaderRoute: typeof AuthenticatedAdminPedidosCompraIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos-compra/novo': {
      id: '/_authenticated/admin/pedidos-compra/novo'
      path: '/pedidos-compra/novo'
      fullPath: '/admin/pedidos-compra/novo'
      preLoaderRoute: typeof AuthenticatedAdminPedidosCompraNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos/$id': {
      id: '/_authenticated/admin/pedidos/$id'
      path: '/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedAdminPedidosIdRouteImport
      parentRoute: typeof AuthenticatedAdminPedidosRoute
    }
    '/_authenticated/admin/produtos/': {
      id: '/_authenticated/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AuthenticatedAdminProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produtos/$id': {
      id: '/_authenticated/admin/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AuthenticatedAdminProdutosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produtos/novo': {
      id: '/_authenticated/admin/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AuthenticatedAdminProdutosNovoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recebimentos/': {
      id: '/_authenticated/admin/recebimentos/'
      path: '/recebimentos'
      fullPath: '/admin/recebimentos/'
      preLoaderRoute: typeof AuthenticatedAdminRecebimentosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recebimentos/$id': {
      id: '/_authenticated/admin/recebimentos/$id'
      path: '/recebimentos/$id'
      fullPath: '/admin/recebimentos/$id'
      preLoaderRoute: typeof AuthenticatedAdminRecebimentosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/saneamento/aliases': {
      id: '/_authenticated/admin/saneamento/aliases'
      path: '/aliases'
      fullPath: '/admin/saneamento/aliases'
      preLoaderRoute: typeof AuthenticatedAdminSaneamentoAliasesRouteImport
      parentRoute: typeof AuthenticatedAdminSaneamentoRoute
    }
    '/_authenticated/admin/vendedores/novo': {
      id: '/_authenticated/admin/vendedores/novo'
      path: '/novo'
      fullPath: '/admin/vendedores/novo'
      preLoaderRoute: typeof AuthenticatedAdminVendedoresNovoRouteImport
      parentRoute: typeof AuthenticatedAdminVendedoresRoute
    }
    '/api/public/bling/callback': {
      id: '/api/public/bling/callback'
      path: '/api/public/bling/callback'
      fullPath: '/api/public/bling/callback'
      preLoaderRoute: typeof ApiPublicBlingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/pedidos-compra/editar/$id': {
      id: '/_authenticated/admin/pedidos-compra/editar/$id'
      path: '/pedidos-compra/editar/$id'
      fullPath: '/admin/pedidos-compra/editar/$id'
      preLoaderRoute: typeof AuthenticatedAdminPedidosCompraEditarIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/stone/conciliation/webhook': {
      id: '/api/public/stone/conciliation/webhook'
      path: '/api/public/stone/conciliation/webhook'
      fullPath: '/api/public/stone/conciliation/webhook'
      preLoaderRoute: typeof ApiPublicStoneConciliationWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminEcossistemaRouteChildren {
  AuthenticatedAdminEcossistemaSlugRoute: typeof AuthenticatedAdminEcossistemaSlugRoute
  AuthenticatedAdminEcossistemaBlingRoute: typeof AuthenticatedAdminEcossistemaBlingRoute
  AuthenticatedAdminEcossistemaIndexRoute: typeof AuthenticatedAdminEcossistemaIndexRoute
}

const AuthenticatedAdminEcossistemaRouteChildren: AuthenticatedAdminEcossistemaRouteChildren =
  {
    AuthenticatedAdminEcossistemaSlugRoute:
      AuthenticatedAdminEcossistemaSlugRoute,
    AuthenticatedAdminEcossistemaBlingRoute:
      AuthenticatedAdminEcossistemaBlingRoute,
    AuthenticatedAdminEcossistemaIndexRoute:
      AuthenticatedAdminEcossistemaIndexRoute,
  }

const AuthenticatedAdminEcossistemaRouteWithChildren =
  AuthenticatedAdminEcossistemaRoute._addFileChildren(
    AuthenticatedAdminEcossistemaRouteChildren,
  )

interface AuthenticatedAdminPedidosRouteChildren {
  AuthenticatedAdminPedidosIdRoute: typeof AuthenticatedAdminPedidosIdRoute
}

const AuthenticatedAdminPedidosRouteChildren: AuthenticatedAdminPedidosRouteChildren =
  {
    AuthenticatedAdminPedidosIdRoute: AuthenticatedAdminPedidosIdRoute,
  }

const AuthenticatedAdminPedidosRouteWithChildren =
  AuthenticatedAdminPedidosRoute._addFileChildren(
    AuthenticatedAdminPedidosRouteChildren,
  )

interface AuthenticatedAdminSaneamentoRouteChildren {
  AuthenticatedAdminSaneamentoAliasesRoute: typeof AuthenticatedAdminSaneamentoAliasesRoute
}

const AuthenticatedAdminSaneamentoRouteChildren: AuthenticatedAdminSaneamentoRouteChildren =
  {
    AuthenticatedAdminSaneamentoAliasesRoute:
      AuthenticatedAdminSaneamentoAliasesRoute,
  }

const AuthenticatedAdminSaneamentoRouteWithChildren =
  AuthenticatedAdminSaneamentoRoute._addFileChildren(
    AuthenticatedAdminSaneamentoRouteChildren,
  )

interface AuthenticatedAdminVendedoresRouteChildren {
  AuthenticatedAdminVendedoresNovoRoute: typeof AuthenticatedAdminVendedoresNovoRoute
}

const AuthenticatedAdminVendedoresRouteChildren: AuthenticatedAdminVendedoresRouteChildren =
  {
    AuthenticatedAdminVendedoresNovoRoute:
      AuthenticatedAdminVendedoresNovoRoute,
  }

const AuthenticatedAdminVendedoresRouteWithChildren =
  AuthenticatedAdminVendedoresRoute._addFileChildren(
    AuthenticatedAdminVendedoresRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminBlingRoute: typeof AuthenticatedAdminBlingRoute
  AuthenticatedAdminCadastrosB2bRoute: typeof AuthenticatedAdminCadastrosB2bRoute
  AuthenticatedAdminCatalogoFabricantesRoute: typeof AuthenticatedAdminCatalogoFabricantesRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminEcossistemaRoute: typeof AuthenticatedAdminEcossistemaRouteWithChildren
  AuthenticatedAdminEnriquecimentoProdutosRoute: typeof AuthenticatedAdminEnriquecimentoProdutosRoute
  AuthenticatedAdminEstoqueRoute: typeof AuthenticatedAdminEstoqueRoute
  AuthenticatedAdminExpedicaoRoute: typeof AuthenticatedAdminExpedicaoRoute
  AuthenticatedAdminFiliaisRoute: typeof AuthenticatedAdminFiliaisRoute
  AuthenticatedAdminFiscalRoute: typeof AuthenticatedAdminFiscalRoute
  AuthenticatedAdminFiscalProdutosRoute: typeof AuthenticatedAdminFiscalProdutosRoute
  AuthenticatedAdminFornecedoresRoute: typeof AuthenticatedAdminFornecedoresRoute
  AuthenticatedAdminHistoricoCustosRoute: typeof AuthenticatedAdminHistoricoCustosRoute
  AuthenticatedAdminHomologacaoRoute: typeof AuthenticatedAdminHomologacaoRoute
  AuthenticatedAdminIaAesBusinessRoute: typeof AuthenticatedAdminIaAesBusinessRoute
  AuthenticatedAdminInteligenciaComercialRoute: typeof AuthenticatedAdminInteligenciaComercialRoute
  AuthenticatedAdminMarcasRoute: typeof AuthenticatedAdminMarcasRoute
  AuthenticatedAdminMigracaoBlingRoute: typeof AuthenticatedAdminMigracaoBlingRoute
  AuthenticatedAdminOrcamentosRoute: typeof AuthenticatedAdminOrcamentosRoute
  AuthenticatedAdminPdvRoute: typeof AuthenticatedAdminPdvRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRouteWithChildren
  AuthenticatedAdminPromocoesRoute: typeof AuthenticatedAdminPromocoesRoute
  AuthenticatedAdminReposicaoRoute: typeof AuthenticatedAdminReposicaoRoute
  AuthenticatedAdminRevisaoCodigosRoute: typeof AuthenticatedAdminRevisaoCodigosRoute
  AuthenticatedAdminSaneamentoRoute: typeof AuthenticatedAdminSaneamentoRouteWithChildren
  AuthenticatedAdminSaneamentoCustosRoute: typeof AuthenticatedAdminSaneamentoCustosRoute
  AuthenticatedAdminSuprimentosRoute: typeof AuthenticatedAdminSuprimentosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminVendedoresRoute: typeof AuthenticatedAdminVendedoresRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminNfeImportacaoIdRoute: typeof AuthenticatedAdminNfeImportacaoIdRoute
  AuthenticatedAdminPedidosCompraIdRoute: typeof AuthenticatedAdminPedidosCompraIdRoute
  AuthenticatedAdminPedidosCompraNovoRoute: typeof AuthenticatedAdminPedidosCompraNovoRoute
  AuthenticatedAdminProdutosIdRoute: typeof AuthenticatedAdminProdutosIdRoute
  AuthenticatedAdminProdutosNovoRoute: typeof AuthenticatedAdminProdutosNovoRoute
  AuthenticatedAdminRecebimentosIdRoute: typeof AuthenticatedAdminRecebimentosIdRoute
  AuthenticatedAdminNfeImportacaoIndexRoute: typeof AuthenticatedAdminNfeImportacaoIndexRoute
  AuthenticatedAdminPedidosCompraIndexRoute: typeof AuthenticatedAdminPedidosCompraIndexRoute
  AuthenticatedAdminProdutosIndexRoute: typeof AuthenticatedAdminProdutosIndexRoute
  AuthenticatedAdminRecebimentosIndexRoute: typeof AuthenticatedAdminRecebimentosIndexRoute
  AuthenticatedAdminPedidosCompraEditarIdRoute: typeof AuthenticatedAdminPedidosCompraEditarIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminBlingRoute: AuthenticatedAdminBlingRoute,
  AuthenticatedAdminCadastrosB2bRoute: AuthenticatedAdminCadastrosB2bRoute,
  AuthenticatedAdminCatalogoFabricantesRoute:
    AuthenticatedAdminCatalogoFabricantesRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
  AuthenticatedAdminEcossistemaRoute:
    AuthenticatedAdminEcossistemaRouteWithChildren,
  AuthenticatedAdminEnriquecimentoProdutosRoute:
    AuthenticatedAdminEnriquecimentoProdutosRoute,
  AuthenticatedAdminEstoqueRoute: AuthenticatedAdminEstoqueRoute,
  AuthenticatedAdminExpedicaoRoute: AuthenticatedAdminExpedicaoRoute,
  AuthenticatedAdminFiliaisRoute: AuthenticatedAdminFiliaisRoute,
  AuthenticatedAdminFiscalRoute: AuthenticatedAdminFiscalRoute,
  AuthenticatedAdminFiscalProdutosRoute: AuthenticatedAdminFiscalProdutosRoute,
  AuthenticatedAdminFornecedoresRoute: AuthenticatedAdminFornecedoresRoute,
  AuthenticatedAdminHistoricoCustosRoute:
    AuthenticatedAdminHistoricoCustosRoute,
  AuthenticatedAdminHomologacaoRoute: AuthenticatedAdminHomologacaoRoute,
  AuthenticatedAdminIaAesBusinessRoute: AuthenticatedAdminIaAesBusinessRoute,
  AuthenticatedAdminInteligenciaComercialRoute:
    AuthenticatedAdminInteligenciaComercialRoute,
  AuthenticatedAdminMarcasRoute: AuthenticatedAdminMarcasRoute,
  AuthenticatedAdminMigracaoBlingRoute: AuthenticatedAdminMigracaoBlingRoute,
  AuthenticatedAdminOrcamentosRoute: AuthenticatedAdminOrcamentosRoute,
  AuthenticatedAdminPdvRoute: AuthenticatedAdminPdvRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRouteWithChildren,
  AuthenticatedAdminPromocoesRoute: AuthenticatedAdminPromocoesRoute,
  AuthenticatedAdminReposicaoRoute: AuthenticatedAdminReposicaoRoute,
  AuthenticatedAdminRevisaoCodigosRoute: AuthenticatedAdminRevisaoCodigosRoute,
  AuthenticatedAdminSaneamentoRoute:
    AuthenticatedAdminSaneamentoRouteWithChildren,
  AuthenticatedAdminSaneamentoCustosRoute:
    AuthenticatedAdminSaneamentoCustosRoute,
  AuthenticatedAdminSuprimentosRoute: AuthenticatedAdminSuprimentosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminVendedoresRoute:
    AuthenticatedAdminVendedoresRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminNfeImportacaoIdRoute:
    AuthenticatedAdminNfeImportacaoIdRoute,
  AuthenticatedAdminPedidosCompraIdRoute:
    AuthenticatedAdminPedidosCompraIdRoute,
  AuthenticatedAdminPedidosCompraNovoRoute:
    AuthenticatedAdminPedidosCompraNovoRoute,
  AuthenticatedAdminProdutosIdRoute: AuthenticatedAdminProdutosIdRoute,
  AuthenticatedAdminProdutosNovoRoute: AuthenticatedAdminProdutosNovoRoute,
  AuthenticatedAdminRecebimentosIdRoute: AuthenticatedAdminRecebimentosIdRoute,
  AuthenticatedAdminNfeImportacaoIndexRoute:
    AuthenticatedAdminNfeImportacaoIndexRoute,
  AuthenticatedAdminPedidosCompraIndexRoute:
    AuthenticatedAdminPedidosCompraIndexRoute,
  AuthenticatedAdminProdutosIndexRoute: AuthenticatedAdminProdutosIndexRoute,
  AuthenticatedAdminRecebimentosIndexRoute:
    AuthenticatedAdminRecebimentosIndexRoute,
  AuthenticatedAdminPedidosCompraEditarIdRoute:
    AuthenticatedAdminPedidosCompraEditarIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedVendedorRouteChildren {
  AuthenticatedVendedorClientesRoute: typeof AuthenticatedVendedorClientesRoute
  AuthenticatedVendedorMeusPedidosRoute: typeof AuthenticatedVendedorMeusPedidosRoute
  AuthenticatedVendedorPedidoAssistidoRoute: typeof AuthenticatedVendedorPedidoAssistidoRoute
  AuthenticatedVendedorIndexRoute: typeof AuthenticatedVendedorIndexRoute
}

const AuthenticatedVendedorRouteChildren: AuthenticatedVendedorRouteChildren = {
  AuthenticatedVendedorClientesRoute: AuthenticatedVendedorClientesRoute,
  AuthenticatedVendedorMeusPedidosRoute: AuthenticatedVendedorMeusPedidosRoute,
  AuthenticatedVendedorPedidoAssistidoRoute:
    AuthenticatedVendedorPedidoAssistidoRoute,
  AuthenticatedVendedorIndexRoute: AuthenticatedVendedorIndexRoute,
}

const AuthenticatedVendedorRouteWithChildren =
  AuthenticatedVendedorRoute._addFileChildren(
    AuthenticatedVendedorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedVendedorRoute: typeof AuthenticatedVendedorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedVendedorRoute: AuthenticatedVendedorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AtivacaoRoute: AtivacaoRoute,
  AuthRoute: AuthRoute,
  B2bRoute: B2bRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  McpRoute: McpRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiHealthRoute: ApiHealthRoute,
  BrandSocialDotwebpRoute: BrandSocialDotwebpRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicLoginRoute: ApiPublicLoginRoute,
  ApiPublicBlingCallbackRoute: ApiPublicBlingCallbackRoute,
  ApiPublicStoneConciliationWebhookRoute:
    ApiPublicStoneConciliationWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
