-- Authentication/API/PII hardening.
-- Passwords remain managed by Supabase Auth (bcrypt hashes); never store reversible passwords.

create schema if not exists private;

create table if not exists public.auth_login_attempts (
  id bigint generated by default as identity primary key,
  identifier_hash text not null,
  ip_hash text not null,
  success boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists auth_login_attempts_identifier_created_idx
  on public.auth_login_attempts (identifier_hash, created_at desc);
create index if not exists auth_login_attempts_ip_created_idx
  on public.auth_login_attempts (ip_hash, created_at desc);

alter table public.auth_login_attempts enable row level security;
revoke all on table public.auth_login_attempts from public, anon, authenticated;
grant select, insert, delete on table public.auth_login_attempts to service_role;
revoke all on sequence public.auth_login_attempts_id_seq from public, anon, authenticated;
grant usage, select on sequence public.auth_login_attempts_id_seq to service_role;

drop policy if exists auth_login_attempts_deny_clients on public.auth_login_attempts;
create policy auth_login_attempts_deny_clients
on public.auth_login_attempts
for all
to anon, authenticated
using (false)
with check (false);

-- Minimize the Data API attack surface even where RLS already denies rows.
revoke all on table public.profiles from anon;
revoke all on table public.user_roles from anon;
revoke all on table public.b2b_registrations from anon;
revoke all on table public.bling_config from anon;
revoke all on table public.bling_sync_logs from anon;
revoke all on table public.integration_settings from anon;
revoke all on table public.integration_logs from anon;
revoke all on table public.integrations from anon;
revoke all on table public.ai_aes_config from anon;
revoke all on table public.ai_chat_sessions from anon;
revoke all on table public.ai_chat_messages from anon;
revoke all on table public.ai_tool_logs from anon;

create table if not exists private.user_private_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  phone_ciphertext bytea,
  key_version smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
revoke all on table private.user_private_data from public, anon, authenticated;
grant select, insert, update, delete on table private.user_private_data to service_role;

do $$
begin
  if not exists (
    select 1 from vault.decrypted_secrets where name = 'norte_sul_user_pii_master_key_v1'
  ) then
    perform vault.create_secret(
      encode(extensions.gen_random_bytes(32), 'hex'),
      'norte_sul_user_pii_master_key_v1',
      'Master key for application-level encryption of Norte Sul user PII'
    );
  end if;
end
$$;

create or replace function private.user_pii_key_v1()
returns text language sql security definer set search_path = '' as $$
  select decrypted_secret from vault.decrypted_secrets
  where name = 'norte_sul_user_pii_master_key_v1' limit 1
$$;
revoke all on function private.user_pii_key_v1() from public, anon, authenticated;

create or replace function private.encrypt_user_pii(value text)
returns bytea language sql security definer set search_path = '' as $$
  select case when value is null or btrim(value) = '' then null
    else extensions.pgp_sym_encrypt(
      btrim(value), private.user_pii_key_v1(),
      'cipher-algo=aes256,compress-algo=0'
    ) end
$$;

create or replace function private.decrypt_user_pii(value bytea)
returns text language sql security definer set search_path = '' as $$
  select case when value is null then null
    else extensions.pgp_sym_decrypt(value, private.user_pii_key_v1()) end
$$;
revoke all on function private.encrypt_user_pii(text) from public, anon, authenticated;
revoke all on function private.decrypt_user_pii(bytea) from public, anon, authenticated;

-- One-time migration of any legacy plaintext phones.
insert into private.user_private_data (user_id, phone_ciphertext, updated_at)
select id, private.encrypt_user_pii(phone), now()
from public.profiles
where phone is not null and btrim(phone) <> ''
on conflict (user_id) do update
set phone_ciphertext = excluded.phone_ciphertext, updated_at = now();

update public.profiles set phone = null where phone is not null;

-- Remove legacy phone duplication from Auth metadata if it exists.
update auth.users
set raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb) - 'phone'
where coalesce(raw_user_meta_data, '{}'::jsonb) ? 'phone';

create or replace function private.capture_profile_phone()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    if new.phone is not null then
      insert into private.user_private_data (user_id, phone_ciphertext, updated_at)
      values (new.id, private.encrypt_user_pii(new.phone), now())
      on conflict (user_id) do update
      set phone_ciphertext = excluded.phone_ciphertext, updated_at = now();
      new.phone := null;
    end if;
  elsif new.phone is distinct from old.phone then
    insert into private.user_private_data (user_id, phone_ciphertext, updated_at)
    values (new.id, private.encrypt_user_pii(new.phone), now())
    on conflict (user_id) do update
    set phone_ciphertext = excluded.phone_ciphertext, updated_at = now();
    new.phone := null;
  end if;
  return new;
end
$$;
revoke all on function private.capture_profile_phone() from public, anon, authenticated;

drop trigger if exists trg_profiles_encrypt_phone on public.profiles;
create trigger trg_profiles_encrypt_phone
before insert or update of phone on public.profiles
for each row execute function private.capture_profile_phone();

create or replace function public.get_my_private_profile()
returns table(full_name text, phone text)
language plpgsql security definer set search_path = '' as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'authentication required' using errcode = '28000'; end if;
  return query
  select p.full_name, private.decrypt_user_pii(up.phone_ciphertext)
  from public.profiles p
  left join private.user_private_data up on up.user_id = p.id
  where p.id = uid;
end
$$;
revoke all on function public.get_my_private_profile() from public, anon;
grant execute on function public.get_my_private_profile() to authenticated;

create or replace function public.update_my_private_profile(p_full_name text, p_phone text)
returns void language plpgsql security definer set search_path = '' as $$
declare
  uid uuid := auth.uid();
  normalized_name text := nullif(btrim(p_full_name), '');
begin
  if uid is null then raise exception 'authentication required' using errcode = '28000'; end if;
  if normalized_name is not null and length(normalized_name) > 160 then raise exception 'invalid full name'; end if;
  if p_phone is not null and length(btrim(p_phone)) > 40 then raise exception 'invalid phone'; end if;

  insert into public.profiles (id, full_name, phone)
  values (uid, normalized_name, null)
  on conflict (id) do update set full_name = excluded.full_name, updated_at = now();

  insert into private.user_private_data (user_id, phone_ciphertext, updated_at)
  values (uid, private.encrypt_user_pii(p_phone), now())
  on conflict (user_id) do update
  set phone_ciphertext = excluded.phone_ciphertext, updated_at = now();
end
$$;
revoke all on function public.update_my_private_profile(text, text) from public, anon;
grant execute on function public.update_my_private_profile(text, text) to authenticated;

create or replace function public.admin_get_user_private_phones(p_user_ids uuid[])
returns table(user_id uuid, phone text)
language plpgsql security definer set search_path = '' as $$
begin
  if auth.role() <> 'service_role' then raise exception 'service role required' using errcode = '42501'; end if;
  return query
  select up.user_id, private.decrypt_user_pii(up.phone_ciphertext)
  from private.user_private_data up where up.user_id = any(p_user_ids);
end
$$;
revoke all on function public.admin_get_user_private_phones(uuid[]) from public, anon, authenticated;
grant execute on function public.admin_get_user_private_phones(uuid[]) to service_role;

create or replace function public.admin_save_user_private_phone(p_user_id uuid, p_phone text)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if auth.role() <> 'service_role' then raise exception 'service role required' using errcode = '42501'; end if;
  if p_phone is not null and length(btrim(p_phone)) > 40 then raise exception 'invalid phone'; end if;
  insert into private.user_private_data (user_id, phone_ciphertext, updated_at)
  values (p_user_id, private.encrypt_user_pii(p_phone), now())
  on conflict (user_id) do update
  set phone_ciphertext = excluded.phone_ciphertext, updated_at = now();
end
$$;
revoke all on function public.admin_save_user_private_phone(uuid, text) from public, anon, authenticated;
grant execute on function public.admin_save_user_private_phone(uuid, text) to service_role;

comment on column public.profiles.phone is
  'Legacy compatibility column. Plaintext values are intercepted and encrypted into private.user_private_data.';
