-- Backup and export control center. Operational exports are generated by the
-- application; full database backups remain infrastructure-managed.

create table if not exists public.backup_export_jobs (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  export_type text not null check (export_type in ('products','customers','stock','sales','financial','fiscal')),
  file_format text not null check (file_format in ('csv','json')),
  status text not null default 'processing' check (status in ('processing','completed','failed')),
  filters jsonb not null default '{}'::jsonb,
  file_name text,
  row_count integer not null default 0 check (row_count >= 0),
  byte_size bigint not null default 0 check (byte_size >= 0),
  error_message text,
  requested_by uuid not null references auth.users(id) on delete restrict default auth.uid(),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.backup_restore_requests (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  reason text not null check (char_length(btrim(reason)) between 10 and 2000),
  requested_snapshot_at timestamptz not null,
  status text not null default 'requested' check (status in ('requested','reviewing','approved','rejected','completed','cancelled')),
  requested_by uuid not null references auth.users(id) on delete restrict default auth.uid(),
  reviewed_by uuid references auth.users(id) on delete restrict,
  review_notes text check (review_notes is null or char_length(review_notes) <= 4000),
  reviewed_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint restore_reviewer_must_differ check (reviewed_by is null or reviewed_by <> requested_by)
);

create index if not exists backup_export_jobs_tenant_created_idx
  on public.backup_export_jobs(tenant_id, created_at desc);
create index if not exists backup_restore_requests_tenant_created_idx
  on public.backup_restore_requests(tenant_id, created_at desc);

alter table public.backup_export_jobs enable row level security;
alter table public.backup_restore_requests enable row level security;

revoke all on public.backup_export_jobs from anon;
revoke all on public.backup_restore_requests from anon;
grant select, insert, update on public.backup_export_jobs to authenticated;
grant select, insert, update on public.backup_restore_requests to authenticated;

drop policy if exists backup_export_jobs_admin_select on public.backup_export_jobs;
create policy backup_export_jobs_admin_select on public.backup_export_jobs
for select to authenticated
using (private.has_tenant_role(tenant_id, array['owner','admin']::text[]));

drop policy if exists backup_export_jobs_admin_insert on public.backup_export_jobs;
create policy backup_export_jobs_admin_insert on public.backup_export_jobs
for insert to authenticated
with check (
  requested_by = auth.uid()
  and private.has_tenant_role(tenant_id, array['owner','admin']::text[])
);

drop policy if exists backup_export_jobs_admin_update on public.backup_export_jobs;
create policy backup_export_jobs_admin_update on public.backup_export_jobs
for update to authenticated
using (
  requested_by = auth.uid()
  and private.has_tenant_role(tenant_id, array['owner','admin']::text[])
)
with check (
  requested_by = auth.uid()
  and private.has_tenant_role(tenant_id, array['owner','admin']::text[])
);

drop policy if exists backup_restore_requests_admin_select on public.backup_restore_requests;
create policy backup_restore_requests_admin_select on public.backup_restore_requests
for select to authenticated
using (private.has_tenant_role(tenant_id, array['owner','admin']::text[]));

drop policy if exists backup_restore_requests_admin_insert on public.backup_restore_requests;
create policy backup_restore_requests_admin_insert on public.backup_restore_requests
for insert to authenticated
with check (
  requested_by = auth.uid()
  and private.has_tenant_role(tenant_id, array['owner','admin']::text[])
);

drop policy if exists backup_restore_requests_owner_update on public.backup_restore_requests;
create policy backup_restore_requests_owner_update on public.backup_restore_requests
for update to authenticated
using (private.has_tenant_role(tenant_id, array['owner']::text[]))
with check (private.has_tenant_role(tenant_id, array['owner']::text[]));

comment on table public.backup_export_jobs is
  'Auditable history of operational CSV/JSON exports. Does not replace infrastructure database backups.';
comment on table public.backup_restore_requests is
  'Controlled restore requests. Execution is intentionally external and requires review by a different administrator.';

create or replace function private.audit_backup_export_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_organization_id uuid;
begin
  select organization_id into v_organization_id
  from public.tenants where id = new.tenant_id;

  if tg_op = 'INSERT' or old.status is distinct from new.status then
    insert into public.audit_events
      (organization_id, tenant_id, actor_user_id, action, resource_type, resource_id, before_data, after_data, metadata)
    values
      (v_organization_id, new.tenant_id, new.requested_by,
       case when tg_op = 'INSERT' then 'backup.export_requested' else 'backup.export_' || new.status end,
       'backup_export_job', new.id::text,
       case when tg_op = 'UPDATE' then jsonb_build_object('status', old.status) else null end,
       jsonb_build_object('status', new.status, 'export_type', new.export_type, 'file_format', new.file_format,
                          'row_count', new.row_count, 'byte_size', new.byte_size),
       jsonb_build_object('filters', new.filters));
  end if;
  return new;
end
$$;

create or replace function private.audit_backup_restore_request()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_organization_id uuid;
begin
  select organization_id into v_organization_id
  from public.tenants where id = new.tenant_id;
  insert into public.audit_events
    (organization_id, tenant_id, actor_user_id, action, resource_type, resource_id, after_data)
  values
    (v_organization_id, new.tenant_id, new.requested_by, 'backup.restore_requested',
     'backup_restore_request', new.id::text,
     jsonb_build_object('status', new.status, 'requested_snapshot_at', new.requested_snapshot_at));
  return new;
end
$$;

revoke all on function private.audit_backup_export_change() from public, anon, authenticated;
revoke all on function private.audit_backup_restore_request() from public, anon, authenticated;

drop trigger if exists trg_backup_export_audit on public.backup_export_jobs;
create trigger trg_backup_export_audit
after insert or update of status on public.backup_export_jobs
for each row execute function private.audit_backup_export_change();

drop trigger if exists trg_backup_restore_audit on public.backup_restore_requests;
create trigger trg_backup_restore_audit
after insert on public.backup_restore_requests
for each row execute function private.audit_backup_restore_request();
