/**
 * Tenant selection helpers (client-safe).
 *
 * The generated Supabase client is regenerated by the integration and does not
 * carry tenant awareness, so the active storefront/tenant slug lives here.
 */
export const TENANT_HEADER = "x-tenant-slug";

const STORAGE_KEY = "active-tenant-slug";

export const DEFAULT_TENANT_SLUG =
  (import.meta.env.VITE_TENANT_STOREFRONT_SLUG as string | undefined) ?? "norte-sul-real";

export function activeTenantSlug(): string {
  if (typeof window === "undefined") return DEFAULT_TENANT_SLUG;
  try {
    return window.localStorage.getItem(STORAGE_KEY) ?? DEFAULT_TENANT_SLUG;
  } catch {
    return DEFAULT_TENANT_SLUG;
  }
}

export function setActiveTenantSlug(slug: string): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(STORAGE_KEY, slug);
  } catch {
    /* ignore storage failures */
  }
  window.location.reload();
}
